### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by justin2004** [setzer22/jena-clj#2]
hello,

would you be willing to change the license to a variant of the GPL that has a classpath exception?
https://en.wikipedia.org/wiki/GPL_linking_exception#The_classpath_exception

that would save me some time at work as i'd like to use your library.

**Comment by setzer22** [comment]
Sure, no problem! Feel free to use the library, I'll update the license later this week when I find some time.

But please bear in mind I do no longer have time to maintain the library, and it's just a thin wrapper over the Java API, so you might be interested on using that instead.

**Comment by setzer22** [comment]
Hi @justin2004  and sorry for the delay. The library is now using the lesser version of the GNU GPL, which means you can safely import the jar into your project. The only condition is that you must publish any changes or improvements you make to the code of this library. Ideally, that would be through a pull request here, but not necessarily.

Also, please let me know if you find this library useful and would like to step in as a maintainer to keep improving it.

Cheers

**Comment by justin2004** [comment]
thank you!

**Comment by mark-watson** [comment]
Thanks!

Also, I think that I will also be using this library and since you don't have time to support it I will fork your repo so if I need a change I don't want to bug you. If I ever add anything substantial, I will let you know.

**Comment by setzer22** [comment]
Thanks @mark-watson. Let me know if you fork and intend to maintain this :) I'd be happy to transfer ownership of the project

**Comment by mark-watson** [comment]
Thanks @setzer22, but the library does what I need as-is and will probably not be modifying it, unless something ever breaks with a Clojure update, etc.

**Comment by mark-watson** [comment]
BTW, I think that you can clones this issue. Thanks again.

**Comment by setzer22** [comment]
No problem! I'm closing this as suggested since the original question was solved :+1:
